approvedGitRepositories:
  - "https://github.com/lipemat/*"

enableGlobalCache: true

enableScripts: false

nodeLinker: node-modules

npmMinimalAgeGate: 1w

npmPreapprovedPackages:
  - "@lipemat/*"

pnpEnableEsmLoader: false

supportedArchitectures:
  os:
    - current
    - linux
